article/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "article"



urlpatterns = [
    path('dashboard/',views.dashboard, name = "dashboard"),
    path('addarticle/',views.addArticle, name = "addarticle"),
    path('article/<int:id>',views.detail, name = "detail"),
    path('update/<int:id>',views.updateArticle, name = "update"),
    path('delete/<int:id>',views.deleteArticle, name = "delete"),
    path('',views.articles, name = "articles"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index,name="index"),
    path('about/', views.about,name="about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "user"


urlpatterns = [
    path('register/',views.register, name = "register"),
    path('login/',views.loginUser, name = "login"),
    path('logout/',views.logoutUser, name = "logout"),
    
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,verbose_name="Yazar")
    title = models.CharField(max_length=50,verbose_name="Başlık")
    content = RichTextField()
    created_date = models.DateTimeField(auto_now_add= True,verbose_name="Oluşturulma Tarihi")
    article_image = models.FileField(blank = True, null = True,verbose_name="Makaleye Fotoğraf Ekleyin")
    def __str__(self):
        return self.title #return self.title,self.author-- her iki değerde gözükür


class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE,verbose_name="Makale",related_name="comments")        
    comment_author = models.CharField(max_length= 50,verbose_name= "İsim")
    comment_content = models.CharField(max_length=200,verbose_name= "Yorum")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content

user/models.py
from django.db import models

# Create your models here.

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_image"]

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label="Kullanıcı Adı")
    password = forms.CharField(label="Parola",widget=forms.PasswordInput)
    



class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50,label="Kullanıcı Adı")
    password = forms.CharField(max_length=20,label="Parola",widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label="Parolayı Doğrula",widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and (password != confirm):
            raise forms.ValidationError("Parolalar Eşleşmiyor")

        else:
            values = {
            "username": username,
            "password": password
        }    
        return values

article/views.py
from turtle import title
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .forms import ArticleForm 
from django.contrib import messages
from .models import Article
from django.contrib.auth.decorators import login_required
# Create your views here.


def articles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})
    articles = Article.objects.all()

    return render(request,"articles.html",{"articles":articles})

def index(request):
    context = {
        "numbers":[1,2,3,4,5,6]
    }
    return render(request,"index.html",context)

def about(request):
    return render(request,"about.html")   

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles": articles
    }
    return render(request,"dashboard.html",context)

@login_required(login_url = "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Oluşturuldu")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form": form})   


def detail(request,id):
    #article = Article.objects.filter(id = id).first
    article = get_object_or_404(Article,id = id)
    return render(request,"detail.html",{"article": article})


@login_required(login_url = "user:login")
def updateArticle(request,id):

    article = get_object_or_404(Article,id = id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request,"Makale Başarıyla Güncellendi")
        return redirect("article:dashboard")

    return render(request,"update.html",{"form":form})


@login_required(login_url = "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)

    article.delete()

    messages.success(request,"Makale Başarıyla Silindi")

    return redirect("article:dashboard") #article'ın altındaki dashboard urlsine git     

user/views.py
from tkinter.tix import Form
from django.shortcuts import render,redirect

from .forms import LoginForm, RegisterForm

from django.contrib.auth.models import User

from django.contrib.auth import login,authenticate,logout

from django.contrib import messages

# Create your views here.


def register(request):
    form = RegisterForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
            
        newUser = User(username = username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)

        messages.info(request,"Başarıyla Kayıt Oldunuz")

        return redirect("index")
        
    context = {
            "form":form
        }
    return render(request,"register.html",context)





    """
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            newUser = User(username = username)
            newUser.set_password(password)

            newUser.save()
            login(request,newUser)

            return redirect("index")
        
        context = {
            "form":form
        }
        return render(request,"register.html",context)


    else:
        form = RegisterForm()
        context = {
            "form":form
        }
        return render(request,"register.html",context)"""

    """
    form = RegisterForm()
    context = {
        "form": form
    }
    return render(request,"register.html",context)"""

def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form": form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Kullanıcı Adı veya Parola Hatalı")
            return render(request,"login.html",context)

        messages.success(request,"Başarıyla Giriş Yaptınız")
        login(request,user)
        return redirect("index")
            

    return render(request,"login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,"Başarıyla Çıkış Yaptınız")
    return redirect("index")

templates/about.html
{% extends "layout.html" %}



{% block body %}
<h3>Hakkımızda</h3>
<hr>

<p>
    aslkcnosaınvsşodnvbdfob   osıfjvsımsdmvismv   sodvipsdmvkdslvsvn
</p>
{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Oluştur</h3>
        <hr>
        <form method="post"     enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Makale Ekle</button>
        
        
        
        </form>

    </div>
</div>


{% endblock body %}

templates/articles.html
{% extends "layout.html" %}


{% block body %}
<div class="col-lg-8">
<h3>Makaleler</h3>
<hr>
</div>
<div class="col-lg-8"> 
<form>
    {% csrf_token %}
    <input type="text" name="keyword" class="input-sm" maxlength="64" placeholder="Ara...">
    <button type="submit" class="btn btn-danger">Ara</button>



</form>
</div>
{% if articles %}
{% for article in articles  %}
    <div class="col-lg-8">
    <!-- Post content-->
        <article>
        <!-- Post header-->
            <header class="mb-4">
            <!-- Post title-->
                <a href="{% url 'article:detail' article.id %}"><h2 class="fw-bolder mb-1">{{article.title}}</h2></a>
                <hr>
            <!-- Post meta content-->
                <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
                <hr>
            <!-- Post categories-->
                <p class="lead">
                by
                {{article.author.username}}
                </p>
                <hr>
            </header>
            <!--Preview image figure-->
            {% if article.article_image %}
            <a href="{% url 'article:detail' article.id %}"><figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..."></figure></a>
            {% endif %}
        
            <!-- Post content-->
            <section class="mb-5">
            {{article.content|safe|truncatewords:50}}
            <a style="float: right;" href="{% url 'article:detail' article.id %}" class="btn btn-danger">Devamını Oku</a>
            </section>
        </article>
    
    </div>


{% endfor %}



{% else %}
<div class="alert alert-danger">
    Makale bulunamadı

</div>
{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Kontrol Paneli</h3>
<hr>

<p>
    Hoşgeldiniz, <small>{{request.user.username}}</small>

</p>
<hr>
<a class="btn btn-danger" href="/articles/addarticle">Makale Ekle</a>
<hr>
{% if articles %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">id</th>
        <th scope="col">Başlık</th>
        <th scope="col">Yazar</th>
        <th scope="col">Tarih</th>
        <th scope="col">Güncelle</th>
        <th scope="col">Sil</th>
      </tr>
    </thead>
    <tbody>
        {% for article in articles  %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a href="{% url 'article:detail' article.id %}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date}}</td>
            <td><a href="{% url 'article:update' article.id %}" class="btn btn-danger">Güncelle</a></td>
            <td><a href="{% url 'article:delete' article.id %}" class="btn btn-danger">Sil</a></td>
        </tr>
        {% endfor %}
      <!--<tr>
        <th scope="row">1</th>
        <td>Mark</td>
        <td>Otto</td>
        <td>@mdo</td>
      </tr>-->

     
    </tbody>
  </table>
{% else %}
<div class="alert alert-danger">

    Henüz Bir Makaleniz Bulunmuyor
</div>
{% endif %}





{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}


<div class="col-lg-8">
    <!-- Post content-->
    <article>
        <!-- Post header-->
        <header class="mb-4">
            <!-- Post title-->
            <h3 class="fw-bolder mb-1">{{article.title}}</h3>
            <hr>
            <!-- Post meta content-->
            <div class="text-muted fst-italic mb-2">{{article.created_date}}</div>
            <hr>
            <!-- Post categories-->
            <p class="lead">
                by
                {{article.author.username}}
            </p>
            <hr>
        </header>
        <!--Preview image figure-->
        {% if article.article_image %}
        <figure class="mb-4"><img class="img-fluid rounded" src="{{article.article_image.url}}" alt="..."></figure>
        {% endif %}
        
        <!-- Post content-->
        <section class="mb-5">
            {{article.content|safe}}
        </section>
    </article>
    <section class="mb-5">
        {% csrf_token %}
    <div class="card bg-light">
        <div class="card-body">
            <!-- Comment form-->
            <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Yorum Ekle....."></textarea></form>
            <button type="submit" class="btn btn-danger">Ekle</button>
            
            
        </div>
    </div>
</section> 
</div>



{% endblock body %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index' %}">Yb Blog</a>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">Hakkımızda <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:articles' %}">Makaleler</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'article:dashboard' %}">Kontrol Paneli</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
        </li>
        
      {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
        </li>

      {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
        </li>
      </ul>
      
    </div>
  </nav>

templates/includes/posttemplate.html
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">Welcome to Blog Post!</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on January 1, 2021 by Start Bootstrap</div>
                            <!-- Post categories-->
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                            <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                        </header>
                        <!-- Preview image figure-->
                        <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..."></figure>
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">Science is an enterprise that should be cherished as an activity of the free human mind. Because it transforms who we are, how we live, and it gives us an understanding of our place in the universe.</p>
                            <p class="fs-5 mb-4">The universe is large and old, and the ingredients for life as we know it are everywhere, so there's no reason to think that Earth would be unique in that regard. Whether of not the life became intelligent is a different question, and we'll see if we find that.</p>
                            <p class="fs-5 mb-4">If you get asteroids about a kilometer in size, those are large enough and carry enough energy into our system to disrupt transportation, communication, the food chains, and that can be a really bad day on Earth.</p>
                            <h2 class="fw-bolder mb-4 mt-5">I have odd cosmic thoughts every day</h2>
                            <p class="fs-5 mb-4">For me, the most fascinating interface is Twitter. I have odd cosmic thoughts every day and I realized I could hold them to myself or share them with people who might be interested.</p>
                            <p class="fs-5 mb-4">Venus has a runaway greenhouse effect. I kind of want to know what happened there because we're twirling knobs here on Earth without knowing the consequences of it. Mars once had running water. It's bone dry today. Something bad happened there as well.</p>
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4"><textarea class="form-control" rows="3" placeholder="Join the discussion and leave a comment!"></textarea></form>
                                <!-- Comment with nested comments-->
                                <div class="d-flex mb-4">
                                    <!-- Parent comment-->
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        If you're going to lead a space frontier, it has to be government; it'll never be private enterprise. Because the space frontier is dangerous, and it's expensive, and it has unquantified risks.
                                        <!-- Child comment 1-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                And under those conditions, you cannot establish a capital-market evaluation of that enterprise. You can't get investors.
                                            </div>
                                        </div>
                                        <!-- Child comment 2-->
                                        <div class="d-flex mt-4">
                                            <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                                            <div class="ms-3">
                                                <div class="fw-bold">Commenter Name</div>
                                                When you put money directly to a problem, it makes a good headline.
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Single comment-->
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><img class="rounded-circle" src="https://dummyimage.com/50x50/ced4da/6c757d.jpg" alt="..."></div>
                                    <div class="ms-3">
                                        <div class="fw-bold">Commenter Name</div>
                                        When I look at the universe and all the ways the universe wants to kill us, I find it hard to reconcile that with statements of beneficence.
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search">
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            

templates/index.html
{% extends "layout.html" %}
{% block body %}

<div class="jumbotron text-center">
    <h3>Yazılım Bilimi Bloğuna Hoşgeldiniz</h3>
    <p>Bu blogta geliştiriciler olarak blog yazılarınızı paylaşabilirisiniz ve insanlara yardımcı olabilirsiniz.</p>

</div>
<p>

    {% if request.user.is_authenticated %}
        Giriş Yapılmış, {{request.user.username}}
    {% else %}
        Giriş Yapılmamış
    {% endif %}


</p>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Ybblog</title>
</head>
<body>


    {% include "includes/navbar.html" %}

    


    <div style="margin-top: 100px; margin-bottom: 100px;"  class="container">
        {% if messages %}
            
                {% for message in messages %}
                {% if message.tags == "info" %}
                <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}

                
                {% endfor %}
            
        {% endif %}

        {% block body %}
        
        {% endblock body %}

    </div>

    





    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.slim.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script> 
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Giriş Yap</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        
        
        
        </form>

    </div>
</div>



{% endblock body %}

templates/logout.html
{% extends "layout.html" %}

{% block body %}

<h3>Çıkış Yap</h3>
<hr>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Kayıt Ol</h3>
        <hr>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Giriş Yap</button>
        
        
        
        </form>

    </div>
</div>
{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Makale Güncelle</h3>
        <hr>
        <form method="post"     enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-danger">Makale Güncelle</button>
        
        
        
        </form>

    </div>
</div>


{% endblock body %}